### ISSUE TITLE
s it possible that the new version of python is not supported? My python version is 3.10.4

### ISSUE THREAD

**Issue by kan11jia28** [sankethj/z-cam#16]
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.10/site-packages/pyngrok/installer.py", line 94, in install_ngrok
    download_path = _download_file(url, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/pyngrok/installer.py", line 257, in _download_file
    raise e
  File "/home/kali/.local/lib/python3.10/site-packages/pyngrok/installer.py", line 215, in _download_file
    response = urlopen(url, **kwargs)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

**Comment by sankethj** [comment]
Make sure that u have  stable connection.
